INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Grant','Tremenda carrera la que se corrio',1,1);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Peter','Muy justa cuando llego a la meta',2,2);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Nicholas','Increible',3,3);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Hamilton','Sigue siendo el mejor',4,4);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Myles','Tremenda carrera la que se corrio',5,5);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Ray','Tremenda carrera la que se corrio',6,1);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Timothy','Muy justa cuando llego a la meta',7,2);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Kyle','Sigue siendo el mejor',8,3);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Reed','Increible',9,4);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Rogan','Sigue siendo el mejor',10,5);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Richard','Muy justa cuando llego a la meta',11,1);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Kelly','Sigue siendo el mejor',12,2);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'August','Sigue siendo el mejor',13,3);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Scott','Increible',14,4);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'George','Muy justa cuando llego a la meta',15,5);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Timothy','Sigue siendo el mejor',16,1);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Kyle','Increible',17,2);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Reed','Sigue siendo el mejor',18,3);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Rogan','Muy justa cuando llego a la meta',19,4);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Richard','Sigue siendo el mejor',20,5);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'Kelly','dolor',21,1);
INSERT INTO COMENTARIO VALUES (SQ_COME_codigo.nextval,'August','dolor',22,2);
