INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS CASAL',to_date('11/11/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAMA LUISA',to_date('10/03/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J Y D',to_date('22/01/1994','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'VALLITA',to_date('25/11/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS AUDACES',to_date('04/05/2000','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'H.J.C',to_date('23/06/2000','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'REDDY',to_date('15/12/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SPORT SERVICES I',to_date('14/11/1994','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TRIPTICO',to_date('24/12/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FERALICO',to_date('13/01/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'Z.M.',to_date('23/08/2007','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DISRAINA',to_date('24/01/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.R.V.R.',to_date('04/01/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DOÑA TITA',to_date('17/10/2005','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ABRIL',to_date('08/12/2001','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MARES',to_date('13/01/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GUACO',to_date('07/08/2009','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LADY MAC QUEEN',to_date('25/07/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FRENCH AFFAIR III',to_date('27/08/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'THE RUNNERS',to_date('08/12/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS NAIPES I',to_date('30/08/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'KINGSTON',to_date('19/04/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MUBARAK I',to_date('02/05/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'RUFFIAN',to_date('19/05/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ROYS REVENGE',to_date('12/03/1998','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HARAS GRAN SOL',to_date('01/07/2008','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRUPO LEON',to_date('27/06/2010','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PERKINS',to_date('03/09/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ASDRU-ZOE',to_date('25/01/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EL INTERNACIONAL',to_date('02/07/2001','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'M.S. (LR)',to_date('04/10/2000','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MEDIA LUNA',to_date('04/07/1998','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CARMELINA',to_date('22/03/2012','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'L.F.',to_date('31/12/1998','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LA LEONERA',to_date('05/02/2011','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MY BEAUTY',to_date('16/05/1998','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'JOWILDALBE',to_date('05/08/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GONZALEZ VILLEGAS',to_date('03/02/2005','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'JUVIDIC',to_date('08/05/2011','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DAVA',to_date('29/08/2004','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AMPIES',to_date('19/09/2000','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DOBLE L.',to_date('09/09/1998','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HORMIGAS RACING',to_date('18/11/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS BACILE',to_date('10/03/2007','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LAS PIEDRAS-MIL DEPORTES',to_date('08/06/2001','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN AVANCE',to_date('29/06/2011','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAVAREZ ',to_date('19/12/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAME II',to_date('10/01/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'R.B.-27',to_date('09/04/2010','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'WAKU III',to_date('15/12/2013','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'OCEAN BAY',to_date('27/08/1994','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CASIGUA',to_date('09/10/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRUPO EL YANKEE',to_date('12/12/2007','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DIEGO Y SUS AMIGOS',to_date('30/11/1999','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SR. DANIEL MORA I',to_date('22/04/2013','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ANA BARBARA',to_date('17/07/2010','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HARAS EL PEÑON',to_date('08/12/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'E.A.K.-V.A.R.A.',to_date('21/03/1992','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MI JUNKITO',to_date('25/11/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GAMBERRO STABLE-LL',to_date('16/10/2001','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AK-KIN',to_date('07/03/2014','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'QUE ESTRELLA',to_date('06/08/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS INTERGALACTICOS',to_date('30/03/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ZURICH',to_date('20/03/2014','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LARECTAFINAL.COM',to_date('29/05/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PRINCESA ORIANA',to_date('26/07/2011','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ALFA',to_date('14/03/2008','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN ALIANZA',to_date('31/10/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LEGAL',to_date('15/05/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'M. ALEJANDRO',to_date('21/09/1991','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.G.',to_date('01/11/2007','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAXI (C)',to_date('12/09/2000','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAZAL-TOV',to_date('31/12/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS AMICI',to_date('09/12/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SECRETARIAT',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'NIÑO RENZO I',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'INRRUCA',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAN GABRIEL II',to_date('02/04/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN DERBY',to_date('01/11/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GENIO',to_date('04/05/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J.A.C.H.',to_date('31/12/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'E.V.S. I',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EL GRAN DIEGO I',to_date('02/04/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'IVANWILL',to_date('01/11/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CABALLEROS-DESPAÑA',to_date('11/10/2014','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ARMANDO RODRIGUEZ',to_date('09/12/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'BUEN AMIGO',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TRANSFORMERS',to_date('20/01/2008','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MARCEVAL',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'G.N.G.',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAN GABRIEL',to_date('02/04/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS FANTASTICOS',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MONTE PIEDAD',to_date('20/01/2008','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'YERBABUENA (C)',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CUATRO GE',to_date('01/11/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PENSAMIENTO VERTICAL',to_date('11/10/2014','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SR. IVAN TENIA',to_date('31/12/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PURO SENTIMIENTO',to_date('09/12/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MASQUEIRAS',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J.A.V.',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GARCIA PETION',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.H. PAVAROTTIS',to_date('01/11/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'POCA-OCTAGON I',to_date('04/05/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PODEROSA',to_date('31/12/2006','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AGAIN',to_date('09/12/1996','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EMCA',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAAB',to_date('11/10/2014','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ANTAKIPRO Y SCRANYER',to_date('04/05/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HOSTAL',to_date('10/09/1995','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'QUOVIS',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MANONA I',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ROB-JOR',to_date('02/04/2015','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'D.E.M.',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS DE VILLA',to_date('08/10/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AGA-CAR-LEO-SAN-ZUB',to_date('25/12/2003','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FOR RACE',to_date('24/12/1997','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TEAM JOSH Y D.J.',to_date('13/01/2002','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'STILOS Y MI GRAN HIJO',to_date('24/01/1993','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LEO-FER',to_date('17/10/2005','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MY SOCIETY',to_date('07/06/2007','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PERIQUITO',to_date('12/04/2013','dd-mm-yyyy'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'THE ACE',to_date('08/12/2001','dd-mm-yyyy'));


delete from stud;