INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS CASAL',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAMA LUISA',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J & D',(TO_DATE('1994-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'VALLITA',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS AUDACES',(TO_DATE('2000-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'H.J.C',(TO_DATE('2000-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'REDDY',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SPORT SERVICES I',(TO_DATE('1994-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TRIPTICO',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FERALICO',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'Z.M.',(TO_DATE('2007-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DISRAINA',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.R.V.R.',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DOÑA TITA',(TO_DATE('2005-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ABRIL',(TO_DATE('2001-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MARES',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GUACO',(TO_DATE('2009-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LADY MAC QUEEN',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FRENCH AFFAIR III',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'THE RUNNERS',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS NAIPES I',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'KINGSTON',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MUBARAK I',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'RUFFIAN',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ROYS REVENGE',(TO_DATE('1998-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HARAS GRAN SOL',(TO_DATE('2008-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRUPO LEON',(TO_DATE('2010-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PERKINS',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ASDRU-ZOE',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EL INTERNACIONAL',(TO_DATE('2001-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'M.S. (LR)',(TO_DATE('2000-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MEDIA LUNA',(TO_DATE('1998-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CARMELINA',(TO_DATE('2012-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'L.F.',(TO_DATE('1998-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LA LEONERA',(TO_DATE('2011-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MY BEAUTY',(TO_DATE('1998-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'JOWILDALBE',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GONZALEZ VILLEGAS',(TO_DATE('2005-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'JUVIDIC',(TO_DATE('2011-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DAVA',(TO_DATE('2004-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AMPIES',(TO_DATE('2000-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DOBLE L.',(TO_DATE('1998-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HORMIGAS RACING',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS BACILE',(TO_DATE('2007-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LAS PIEDRAS-MIL DEPORTES',(TO_DATE('2001-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN AVANCE',(TO_DATE('2011-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAVAREZ ',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAME II',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'R.B.-27',(TO_DATE('2010-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'WAKU III',(TO_DATE('2013-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'OCEAN BAY',(TO_DATE('1994-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CASIGUA',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRUPO EL YANKEE',(TO_DATE('2007-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'DIEGO Y SUS AMIGOS',(TO_DATE('1999-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SR. DANIEL MORA I',(TO_DATE('2013-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ANA BARBARA',(TO_DATE('2010-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HARAS EL PEÑON',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'E.A.K.-V.A.R.A.',(TO_DATE('1992-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MI JUNKITO',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GAMBERRO STABLE-LL',(TO_DATE('2001-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AK-KIN',(TO_DATE('2014-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'QUE ESTRELLA',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS INTERGALACTICOS',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ZURICH',(TO_DATE('2014-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LARECTAFINAL.COM',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PRINCESA ORIANA',(TO_DATE('2011-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ALFA',(TO_DATE('2008-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN ALIANZA',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LEGAL',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'M. ALEJANDRO',(TO_DATE('1991-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.G.',(TO_DATE('2007-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAXI (C)',(TO_DATE('2000-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MAZAL-TOV',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS AMICI',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SECRETARIAT',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'NIÑO RENZO I',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'INRRUCA',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAN GABRIEL II',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GRAN DERBY',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GENIO',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J.A.C.H.',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'E.V.S. I',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EL GRAN DIEGO I',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'IVANWILL',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CABALLEROS-DESPAÑA',(TO_DATE('2014-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ARMANDO RODRIGUEZ',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'BUEN AMIGO',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TRANSFORMERS',(TO_DATE('2008-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MARCEVAL',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'G.N.G.',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAN GABRIEL',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS FANTASTICOS',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MONTE PIEDAD',(TO_DATE('2008-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'YERBABUENA (C)',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'CUATRO GE',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PENSAMIENTO VERTICAL',(TO_DATE('2014-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SR. IVAN TENIA',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PURO SENTIMIENTO',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MASQUEIRAS',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'J.A.V.',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'GARCIA PETION',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'C.H. PAVAROTTIS',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'POCA-OCTAGON I',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PODEROSA',(TO_DATE('2006-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AGAIN',(TO_DATE('1996-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'EMCA',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'SAAB',(TO_DATE('2014-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ANTAKIPRO & SCRANYER',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'HOSTAL',(TO_DATE('1995-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'QUOVIS',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MANONA I',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'ROB-JOR',(TO_DATE('2015-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'D.E.M.',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LOS DE VILLA',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'AGA-CAR-LEO-SAN-ZUB',(TO_DATE('2003-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'FOR RACE',(TO_DATE('1997-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'TEAM JOSH & D.J.',(TO_DATE('2002-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'STILOS & MI GRAN HIJO',(TO_DATE('1993-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'LEO-FER',(TO_DATE('2005-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'MY SOCIETY',(TO_DATE('2007-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'PERIQUITO',(TO_DATE('2013-11-11',('yyyy-mm-dd'));
INSERT INTO STUD VALUES (SQ_STUD_codigo.nextval,'THE ACE',(TO_DATE('2001-11-11',('yyyy-mm-dd'));
