INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,1,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,2,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,3,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,4,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,5,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,6,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,7,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,8,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,9,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,10,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,11,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,12,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,13,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,14,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,15,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,16,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,17,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,18,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,19,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,20,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Lenin'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,21,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,22,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,23,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,24,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,25,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,26,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,27,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,28,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,29,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,30,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,31,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,32,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,33,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,34,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,35,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,36,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,37,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Alexandra'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,38,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,39,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,40,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,41,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,42,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,43,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,44,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,45,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,46,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,47,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,48,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,49,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Humberto'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,50,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,51,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,52,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,53,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,54,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,55,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,56,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,57,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,58,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,59,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,60,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,61,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,62,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,63,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,64,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,65,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,66,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,67,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,68,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,69,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,70,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Miguel'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,71,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,72,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,73,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,74,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,75,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,76,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Rubén'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,77,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,78,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,79,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,80,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,81,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,82,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,83,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Alexis'),(select VETE_codigo from veterinario where VETE_nombre='Ana'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,84,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,85,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,86,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,87,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,88,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,89,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,90,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,91,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,92,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,93,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,94,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,95,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,96,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,97,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,98,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,99,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,100,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,101,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,102,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,103,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,104,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,105,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,106,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,107,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,108,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,109,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Daniela'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,110,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,111,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,112,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,113,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,114,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,115,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,116,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,117,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,118,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,119,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,120,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,121,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,122,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,123,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,124,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,125,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,126,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,127,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,128,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,129,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,130,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,131,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ernesto'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,132,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,133,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,134,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,135,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,136,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,137,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,138,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Jesus'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,139,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,140,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,141,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,142,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,143,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,144,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,145,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,146,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,147,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,148,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Ramón'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,149,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,150,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Alejandro'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,151,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,152,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,153,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,154,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,155,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,156,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,157,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,158,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,159,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,160,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,161,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,162,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,163,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,164,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,165,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,166,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Asdrúbal J'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,167,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,168,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,169,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,170,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,171,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,172,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,173,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,174,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,175,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Fernando'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,176,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='José G'),(select VETE_codigo from veterinario where VETE_nombre='Carolina'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,177,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,178,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,179,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,180,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,181,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,182,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,183,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,184,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,185,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,186,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,187,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,188,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,189,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,190,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,191,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,192,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,193,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,194,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,195,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,196,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,197,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,198,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,199,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,200,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,201,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Miguel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,202,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,203,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,204,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,205,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,206,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,207,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,208,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,209,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,210,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,211,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,212,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,213,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Cesar'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,214,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,215,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Jose F'),(select VETE_codigo from veterinario where VETE_nombre='Samuel'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,216,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,217,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,218,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,219,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Gilberto'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,220,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,221,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,222,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,223,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,224,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));
INSERT INTO CABALLERIZA VALUES(SQ_CABA_codigo.nextval,225,(select ENTR_codigo from ENTRENADOR where ENTR_nombre='Morris'),(select VETE_codigo from veterinario where VETE_nombre='Thais'));