INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Buta');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Lasix');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Legend');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Arterol');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Artrocon');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Salix');
INSERT INTO MEDICAMENTO VALUES(SQ_MEDI_codigo.nextval,'Uronort');