INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre= 'Harrell')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hyde')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Woodward')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Dillard')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Wagner')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Goodwin')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Farmer')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Russell')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Payne')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hancock')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Schneider')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sims')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Andrews')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Barr')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Short')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Marquez')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Heath')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Taylor')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haney')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Goodwin')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hayes')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pace')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Wilder')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tanner')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hansen')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Reilly')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lopez')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sawyer')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Marks')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kelly')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Witt')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Robertson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Monroe')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Richard')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Foster')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Castaneda')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kramer')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rodriquez')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Harrell')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Russell')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Baldwin')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rosario')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Day')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Huffman')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Valentine')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tillman')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haley')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Brock')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gentry')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Donovan')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Freeman')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Larson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haney')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Patton')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Fitzpatrick')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Woods')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mcdaniel')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hernandez')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Grimes')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Watson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sanford')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lee')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pearson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Nguyen')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gomez')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Bright')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Burns')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mcclain')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Graves')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Leon')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Knight')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre='	Chaney')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hodge')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Olsen')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ballard')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ferguson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hubbard')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Le')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hardin')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pennington')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tillman')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cole')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tyler')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Barry')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Herring')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Duffy')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kelley')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Logan')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Howard')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pratt')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Stone')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Savage')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kemp')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Roth')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Spencer')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Davidson')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Long')	,(select ROL_codigo from ROL WHERE ROL_nombre=	'administrador'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Bray')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Black')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pena')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Walsh')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Klein')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Oneill')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Conway')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Jenkins')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Shannon')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mccormick')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mccormick')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Orr')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Donaldson')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Herman')	,(select ROL_codigo from ROL WHERE ROL_nombre='Jinete'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Camacho')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Humphrey')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Chavez')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hyde')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Payne')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gilbert')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Norris')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Crosby')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Garner')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Finley')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sykes')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cobb')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Martin')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Holcomb')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Swanson')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Newton')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Murray')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cabrera')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Melendez')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ewing')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Abbott')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Thomas')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Yates')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Roberson')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mckinney')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'England')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sanchez')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lancaster')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kinney')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lambert')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
INSERT INTO ROUS	VALUES  (SQ_ROUS_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tucker')	,(select ROL_codigo from ROL WHERE ROL_nombre='basico'	 ));
