INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'true',(TO_DATE('2015/12/15'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE('2015/12/15'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'true',(TO_DATE('11/12/15'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE('2015/12/17'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE (' 2015/12/11'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE ('2015/12/14'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'true',(TO_DATE('2015/12/13'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE(' 2015/12/12'));
INSERT INTO TRAQUEO VALUES (SQ_TAAP_codigo.nextval,'false',(TO_DATE ('2015/12/10'));
