/*Claves primarias*/
alter table HORA add constraint HORA_pk primary key(HORA_codigo);
alter table HORE add constraint HORE_pk primary key(HORE_codigo);
alter table RESTAURANTE add constraint RESTAURANTE_pk primary key(REST_codigo);
alter table RESA add constraint RESA_pk primary key(RESA_codigo);
alter table COMENTARIO add constraint COMENTARIO_pk primary key(COME_codigo);
alter table COIN add constraint COIN_pk primary key(COIN_codigo);
alter table AREA add constraint AREA_pk primary key(AREA_codigo);
alter table PEAR add constraint PEAR_pk primary key(PEAR_codigo);
alter table MATERIAL add constraint MATERIAL_pk primary key(MATE_codigo);
alter table PISTA add constraint PISTA_pk primary key(PIST_codigo);
alter table COLOR add constraint COLOR_pk primary key(COLO_codigo);
alter table COST add constraint COST_pk primary key(COST_codigo);
alter table CARRERA add constraint CARRERA_pk primary key(CARR_codigo);
alter table STUD add constraint STUD_pk primary key(STUD_codigo);
alter table PRST add constraint PRST_pk primary key(PRST_codigo);
alter table INSCRIPCION add constraint INSCRIPCION_pk primary key(INSC_codigo);
alter table LUGAR add constraint LUGAR_pk primary key(LUGA_codigo);
alter table TELEFONO add constraint TELEFONO_pk primary key(TELE_codigo);
alter table ARTA add constraint ARTA_pk primary key(ARTA_codigo);
alter table PISO add constraint PISO_pk primary key(PISO_codigo);
alter table CAEJ add constraint CAEJ_pk primary key(CAEJ_codigo);
alter table EJEMPLAR add constraint EJEMPLAR_pk primary key(EJEM_codigo);
alter table PROPIETARIO add constraint PROPIETARIO_pk primary key(PROP_codigo);
alter table ENTRENADOR add constraint ENTRENADOR_pk primary key(ENTR_codigo);
alter table VETERINARIO add constraint VETERINARIO_pk primary key(VETE_codigo);
alter table JINETE add constraint JINETE_pk primary key(JINE_codigo);
alter table INVITADO add constraint INVITADO_pk primary key(INVI_codigo);
alter table TAQUILLA add constraint TAQUILLA_pk primary key(TAQU_codigo);
alter table IMCA add constraint IMCA_pk primary key(IMCA_codigo);
alter table IMPLEMENTO add constraint IMPLEMENTO_pk primary key(IMPL_codigo);
alter table POCA add constraint POCA_pk primary key(POCA_codigo);
alter table POSTE add constraint POSTE_pk primary key(POST_codigo);
alter table CAME add constraint CAME_pk primary key(CAME_codigo);
alter table MEDICAMENTO add constraint MEDICAMENTO_pk primary key(MEDI_codigo);
alter table ENCA add constraint ENCA_pk primary key(ENCA_codigo);
alter table ENFERMEDAD add constraint ENFERMEDAD_pk primary key(ENFE_codigo);
alter table PUESTO add constraint PUESTO_pk primary key(PUES_codigo);
alter table CABALLERIZA add constraint CABALLERIZA_pk primary key(CABA_codigo);
alter table EJTR add constraint EJTR_pk primary key(EJTR_codigo);
alter table TRAQUEO add constraint TRAQUEO_pk primary key(TRAQ_codigo);
alter table ENVE add constraint ENVE_pk primary key(ENVE_codigo);
alter table CAAP add constraint CAAP_pk primary key(CAAP_codigo);
alter table USUARIO add constraint USUARIO_pk primary key(USUA_codigo);
alter table ROL add constraint ROL_pk primary key(ROL_codigo);
alter table TAAP add constraint TAAP_pk primary key(TAAP_codigo);
alter table APUESTA add constraint APUESTA_pk primary key(APUE_codigo);

/*Claves foraneas*/
alter table HORE add constraint FK_rest_hore foreign key (FK_REST) references RESTAURANTE(REST_codigo);
alter table HORE add constraint FK_hora_hore foreign key (FK_HORA) references HORA(HORA_codigo);
alter table RESA add constraint FK_area_resa foreign key (FK_area) references AREA(AREA_codigo);
alter table RESA add constraint FK_rest_resa foreign key (FK_REST) references RESTAURANTE(REST_codigo);
alter table COMENTARIO add constraint FK_caej_come foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table COIN add constraint FK_come_coin foreign key (FK_COME) references COMENTARIO(COME_codigo);
alter table COIN add constraint FK_invi_coin foreign key (FK_INVI) references INVITADO(INVI_codigo);
alter table PEAR add constraint FK_prop_pear foreign key (FK_PROP) references PROPIETARIO(PROP_codigo);
alter table PEAR add constraint FK_entr_pear foreign key (FK_ENTR) references ENTRENADOR(ENTR_codigo);
alter table PEAR add constraint FK_vete_pear foreign key (FK_VETE) references VETERINARIO(VETE_codigo);
alter table PEAR add constraint FK_jine_pear foreign key (FK_JINE) references JINETE(JINE_codigo);
alter table PEAR add constraint FK_invi_pear foreign key (FK_INVI) references INVITADO(INVI_codigo);
alter table PEAR add constraint FK_area_pear foreign key (FK_AREA) references AREA(AREA_codigo);
alter table MATERIAL add constraint FK_pist_mate foreign key (FK_PIST) references PISTA(PIST_codigo);
alter table COST add constraint FK_stud_cost foreign key (FK_STUD) references STUD(STUD_codigo);
alter table COST add constraint FK_colo_cost foreign key (FK_COLO) references COLOR(COLO_codigo);
alter table CARRERA add constraint FK_pist_carr foreign key (FK_PIST) references CARRERA(CARR_codigo);
alter table PRST add constraint FK_prop_prst foreign key (FK_PROP) references PROPIETARIO(PROP_codigo);
alter table PRST add constraint FK_stud_prst foreign key (FK_STUD) references STUD(STUD_codigo);
alter table INSCRIPCION add constraint FK_ejem_insc foreign key (FK_EJEM) references EJEMPLAR(EJEM_codigo);
alter table INSCRIPCION add constraint FK_carr_insc foreign key (FK_CARR) references CARRERA(CARR_codigo);
alter table LUGAR add constraint FK_luga_luga foreign key (FK_LUGA) references LUGAR(LUGA_codigo);
alter table TELEFONO add constraint FK_prop_tele foreign key (FK_PROP) references PROPIETARIO(PROP_codigo);
alter table ARTA add constraint FK_area_arta foreign key (FK_AREA) references AREA(AREA_codigo);
alter table ARTA add constraint FK_taqu_arta foreign key (FK_TAQU) references TAQUILLA(TAQU_codigo);
alter table PISO add constraint FK_area_piso foreign key (FK_AREA) references AREA(AREA_codigo);
alter table CAEJ add constraint FK_ejem_caej foreign key (FK_EJEM) references EJEMPLAR(EJEM_codigo);
alter table CAEJ add constraint FK_carr_caej foreign key (FK_CARR) references CARRERA(CARR_codigo);
alter table CAEJ add constraint FK_hora_caej foreign key (FK_HORA) references HORA(HORA_codigo);
alter table EJEMPLAR add constraint FK_ejemm_ejem foreign key (FK_EJEM_M) references EJEMPLAR(EJEM_codigo);
alter table EJEMPLAR add constraint FK_ejemp_ejem foreign key (FK_EJEM_P) references EJEMPLAR(EJEM_codigo);
alter table EJEMPLAR add constraint FK_pues_ejem foreign key (FK_PUES) references PUESTO(PUES_codigo);
alter table EJEMPLAR add constraint FK_prstv_ejem foreign key (FK_PRST_V) references PRST(PRST_codigo);
alter table EJEMPLAR add constraint FK_prstc_ejem foreign key (FK_PRST_C) references PRST(PRST_codigo);
alter table EJEMPLAR add constraint FK_luga_ejem foreign key (FK_LUGA) references LUGAR(LUGA_codigo);
alter table PROPIETARIO add constraint FK_luga_prop foreign key (FK_LUGA) references LUGAR(LUGA_codigo);
alter table PROPIETARIO add constraint FK_usua_prop foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table ENTRENADOR add constraint FK_usua_entr foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table VETERINARIO add constraint FK_usua_vete foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table JINETE add constraint FK_caej_jine foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table JINETE add constraint FK_usua_jine foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table INVITADO add constraint FK_usua_invi foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table IMCA add constraint FK_caej_inca foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table IMCA add constraint FK_impl_inca foreign key (FK_IMPL) references IMPLEMENTO(IMPL_codigo);
alter table POCA add constraint FK_caej_poca foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table POCA add constraint FK_post_poca foreign key (FK_POST) references POSTE(POST_codigo);
alter table CAME add constraint FK_caej_came foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table CAME add constraint FK_medi_came foreign key (FK_MEDI) references MEDICAMENTO(MEDI_codigo);
alter table ENCA add constraint FK_caej_enca foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table ENCA add constraint FK_enfe_enca foreign key (FK_ENFE) references ENFERMEDAD(ENFE_codigo);
alter table PUESTO add constraint FK_caba_pues foreign key (FK_CABA) references CABALLERIZA(CABA_codigo);
alter table CABALLERIZA add constraint FK_vete_caba foreign key (FK_VETE) references VETERINARIO(VETE_codigo);
alter table CABALLERIZA add constraint FK_entr_caba foreign key (FK_ENTR) references ENTRENADOR(ENTR_codigo);
alter table EJTR add constraint FK_ejem_ejtr foreign key (FK_EJEM) references EJEMPLAR(EJEM_codigo);
alter table EJTR add constraint FK_traq_ejtr foreign key (FK_TRAQ) references TRAQUEO(TRAQ_codigo);
alter table ENVE add constraint FK_vete_enve foreign key (FK_VETE) references VETERINARIO(VETE_codigo);
alter table ENVE add constraint FK_enfe_enve foreign key (FK_ENFE) references ENFERMEDAD(ENFE_codigo);
alter table CAAP add constraint FK_caej_caap foreign key (FK_CAEJ) references CAEJ(CAEJ_codigo);
alter table CAAP add constraint FK_taap_caap foreign key (FK_TAAP) references TAAP(TAAP_codigo);
alter table ROL add constraint FK_usua_rol foreign key (FK_USUA) references USUARIO(USUA_codigo);
alter table TAAP add constraint FK_apue_taap foreign key (FK_APUE) references APUESTA(APUE_codigo);
alter table TAAP add constraint FK_taqu_taap foreign key (FK_TAQU) references TAQUILLA(TAQU_codigo);

/*Checks*/
alter table HORA add constraint CH_hora_dia check (HORA_dia IN ('viernes','sabado','domingo'));
alter table AREA add constraint CH_area_tipo check (AREA_tipo IN ('paddock','circulo de ganadores','grada central','tribuna','estacionamiento','butaca','playa','pasillo','palcos'));
alter table COST add constraint CH_cost_tipo check (COST_tipo IN ('gorra','chaquetilla'));
alter table CARRERA add constraint CH_carr_tipo check (CARR_tipo IN ('clasico','normal','copa'));
alter table LUGAR add constraint CH_luga_tipo check (LUGA_tipo IN ('pais','estado','municipio'));
alter table ARTA add constraint CH_arta_puerta check (ARTA_puerta IN ('A','B','C','D','E','F'));
alter table PISO add constraint CH_piso_tipo check (PISO_tipo IN ('nivel 1','nivel 2','mezzanina'));
alter table CAEJ add constraint CH_caej_tipo check (CAEJ_tipo IN ('Reclamo','ganadores de 1 carrera','ganadores de 2 carreras')); /*Revisar esto*/
alter table INVITADO add constraint CH_invi_tipo check (INVI_tipo IN ('artista','deportista','opinion'));
alter table TAQUILLA add constraint CH_taqu_tipo check (TAQU_tipo IN ('apuesta','boleto'));
alter table IMPLEMENTO add constraint CH_impl_tipo check (IMPL_tipo IN ('CC','CH'));

/*Unique*/
alter table PROPIETARIO add constraint UN_prop_cedula unique (PROP_cedula);
alter table PROPIETARIO add constraint UN_prop_email unique (PROP_email);
alter table JINETE add constraint UN_jine_cedula unique (JINE_cedula);
alter table IMPLEMENTO add constraint UN_impl_nombre unique (IMPL_nombre);
alter table MEDICAMENTO add constraint UN_medi_nombre unique (MEDI_nombre);
alter table ENFERMEDAD add constraint UN_enfe_nombre unique (ENFE_nombre);
alter table APUESTA add constraint UN_apue_nombre unique (APUE_nombre);