//INSERTS DE ROUS
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre= ' 	Harrell'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hyde'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Woodward'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Dillard'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Wagner'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Goodwin'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Farmer'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Russell'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Payne'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hancock'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Schneider'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sims'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Andrews'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Barr'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Short'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Marquez'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Heath'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Taylor'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haney'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Goodwin'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hayes'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pace'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Wilder'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tanner'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hansen'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Reilly'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lopez'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sawyer'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Marks'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kelly'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Witt'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Robertson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Monroe'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Richard'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Foster'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Castaneda'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kramer'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rodriquez'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Harrell'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Russell'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Baldwin'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rosario'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Day'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Huffman'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Valentine'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tillman'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haley'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Brock'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gentry'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Donovan'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Freeman'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Larson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Haney'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Patton'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Fitzpatrick'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Woods'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mcdaniel'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hernandez'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Grimes'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Watson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sanford'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lee'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pearson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Nguyen'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gomez'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Bright'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Burns'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mcclain'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Graves'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Leon'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Knight'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre= 'Chaney'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hodge'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Olsen'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ballard'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ferguson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hubbard'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Le'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hardin'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pennington'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tillman'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cole'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tyler'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Barry'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Herring'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Duffy'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kelley'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Rollins'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Logan'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Howard'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pratt'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Stone'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Savage'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kemp'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Roth'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Spencer'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Davidson'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Long'),(select ROL_codig from ROL WHERE ROL_nombre='BLEM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Bray'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Black'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Pena'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Walsh'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Klein'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Oneill'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Conway'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Jenkins'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Shannon'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mccormick'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mccormick'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Orr'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Donaldson'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Herman'),(select ROL_codig from ROL WHERE ROL_nombre='BLM'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Camacho'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Humphrey'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Chavez'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Hyde'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Payne'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Gilbert'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Norris'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Crosby'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Garner'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Finley'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sykes'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cobb'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Martin'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Holcomb'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Swanson'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Newton'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Murray'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Cabrera'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Melendez'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Ewing'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Abbott'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Thomas'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Yates'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Roberson'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Mckinney'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'England'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Sanchez'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lancaster'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Kinney'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Lambert'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));
INSERT INTO ROUS	VALUES  (SQROUSP_codigo.nextval	,(select   USUA_codigo from USUARIO WHERE  USUA_nombre=	'Tucker'),(select ROL_codig from ROL WHERE ROL_nombre='LE'));

//INSERTS DE HARA

INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'Mamoncito'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'San Pablo'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'La Quinta'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'Estados Unidos'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'San Gregorio'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'La Montaña'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));
INSERT INTO HARAS	VALUES(SQ_HARA_codigo.nextval,	'Urama'	,(select LUGA_codigo from LUGAR where LUGA_tipo='CHACAO'));

//INSERTS DE UNIFORME

INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Camisa');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Gorra');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Pantalon');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Casco');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Botas');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Fusta');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Breech');
INSERT INTO UNIFORME VALUES(SQ_UNIF_codigo.nextval,'Blazer');

//INSERTS DE PUESTO


INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),13,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=1));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),5,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),13,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=4));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),8,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=8));
INSERT INTO PUESTO VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=9));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=10));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=10));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=11));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=12));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=13));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=15));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=16));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=17));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=18));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),3,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=19));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=20));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=21));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),13,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),3,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),13,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),3,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=1));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),9,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),6,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=4));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),9,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=11));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=12));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=13));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=15));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=16));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=17));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),8,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=18));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=19));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=20));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=21));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),13,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),8,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=8));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=10));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),16,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=11));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),3,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=12));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=13));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=15));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),6,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=17));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=18));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=20));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=22));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=21));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),16,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),6,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),8,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=4));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),6,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),6,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=6));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=4));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=11));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=13));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),16,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),9,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=2));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=12));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),9,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=17));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=19));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=20));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),7,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=18));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),12,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=16));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=15));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),4),(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=12));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-14')),(TO_DATE('2015-12-17')),14,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=13));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),4,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=14);
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),10,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=3));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),11,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=1));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),15,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-15')),(TO_DATE('2015-12-17')),2,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=7));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval,(TO_DATE('2015-12-16')),(TO_DATE('2015-12-17')),3,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=5));
INSERT INTO PUESTO  VALUES (SQ_TAAP_codigo.nextval0(TO_DATE('2015-12-16')),(TO_DATE(('2015-1-17')),1,(select CABA_codigo from  CABALLERIZA WHERE CABA_numero=11));