CREATE SEQUENCE SQ_AREA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_INVI_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PUES_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PEAR_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_IMPL_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_CAEJ_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_TRAQ_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PIST_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_IMCA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_VETE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_COLO_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ENFE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_HORE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PRST_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ARTA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_REST_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ENVE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_TAAP_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_CAAP_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_CAME_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_STUD_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_APUE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_CABA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ROL_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ENTR_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_POST_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_TELE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_COST_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_INSC_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PISO_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_HORA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_EJEM_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_RESA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_COME_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_JINE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_USUA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_TAQU_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_POCA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_LUGA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_MEDI_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_CARR_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_MATE_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_PROP_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_EJTR_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_COIN_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;
CREATE SEQUENCE SQ_ENCA_codigo
START WITH 1
INCREMENT BY 1
CACHE 1000;