CREATE TABLE HORA (
HORA_codigo		NUMBER(10)	NOT NULL,
HORA_inicio		DATE	NOT NULL,
HORA_fin		DATE	NOT NULL,
HORA_dia		VARCHAR2(20)	NOT NULL
);

CREATE TABLE HORE (
HORE_codigo		NUMBER(10)	NOT NULL,
FK_REST		NUMBER(10)	NOT NULL,
FK_HORA		NUMBER(10)	NOT NULL
);

CREATE TABLE RESTAURANTE (
REST_codigo		NUMBER(10)	NOT NULL,
REST_nombre		VARCHAR2(20)	NOT NULL
);

CREATE TABLE RESA (
RESA_codigo		NUMBER(10)	NOT NULL,
FK_AREA		NUMBER(10)	NOT NULL,
FK_REST		NUMBER(10)	NOT NULL
);

CREATE TABLE COMENTARIO (
COME_codigo		NUMBER(10)	NOT NULL,
COME_nombre		VARCHAR2(20)	NOT NULL,
COME_descripcion		VARCHAR2(50)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_INVI		NUMBER(10)	NOT NULL
);

CREATE TABLE AREA (
AREA_codigo		NUMBER(10)	NOT NULL,
AREA_cantidad		NUMBER(5),
AREA_tipo		VARCHAR2(20)	NOT NULL,
AREA_descripcion		VARCHAR2(20)	NOT NULL
);

CREATE TABLE PEAR (
PEAR_codigo		NUMBER(10)	NOT NULL,
FK_PROP		NUMBER(10),
FK_ENTR		NUMBER(10),
FK_VETE		NUMBER(10),
FK_JINE		NUMBER(10),
FK_INVI		NUMBER(10),
FK_AREA		NUMBER(10)	NOT NULL
);

CREATE TABLE MATERIAL (
MATE_codigo		NUMBER(10)	NOT NULL,
MATE_nombre		VARCHAR2(20)	NOT NULL,
FK_PIST		NUMBER(10)	NOT NULL
);

CREATE TABLE PISTA (
PIST_codigo		NUMBER(10)	NOT NULL,
PIST_longitud		NUMBER(10)	NOT NULL,
PIST_varianza		NUMBER(10)	NOT NULL
);

CREATE TABLE COLOR (
COLO_codigo		NUMBER(10)	NOT NULL,
COLO_nombre		VARCHAR2(15)	NOT NULL
);

CREATE TABLE COST (
COST_codigo		NUMBER(10)	NOT NULL,
FK_STUD		NUMBER(10)	NOT NULL,
FK_COLO		NUMBER(10)	NOT NULL,
FK_UNIF		NUMBER(10)	NOT NULL
);

CREATE TABLE CARRERA (
CARR_codigo		NUMBER(10)	NOT NULL,
CARR_nombre		VARCHAR2(20)	NOT NULL,
CARR_categoria		VARCHAR2(20)	NOT NULL,
CARR_fecha		DATE	NOT NULL,
CARR_num_carrera		NUMBER(16)	NOT NULL,
CARR_lote		VARCHAR2(20)	NOT NULL,
CARR_distancia		NUMBER(10)	NOT NULL,
CARR_variante		NUMBER(10)	NOT NULL,
FK_PIST		NUMBER(10)	NOT NULL,
FK_HORA		NUMBER(10)	NOT NULL
);

CREATE TABLE STUD (
STUD_codigo		NUMBER(10)	NOT NULL,
STUD_nombre		VARCHAR2(20)	NOT NULL,
STUD_fecha_creacion		DATE	NOT NULL
);

CREATE TABLE PRST (
PRST_codigo		NUMBER(10)	NOT NULL,
PRST_porcentaje		NUMBER(5)	NOT NULL,
FK_PROP		NUMBER(10)	NOT NULL,
FK_STUD		NUMBER(10)	NOT NULL,
FK_EJEM		NUMBER(10)	NOT NULL
);

CREATE TABLE LUGAR (
LUGA_codigo		NUMBER(10)	NOT NULL,
LUGA_nombre		VARCHAR2(15)	NOT NULL,
LUGA_tipo		VARCHAR2(20)	NOT NULL,
FK_LUGA		NUMBER(10)
);

CREATE TABLE TELEFONO (
TELE_codigo		NUMBER(10)	NOT NULL,
TELE_numero		NUMBER(10)	NOT NULL,
FK_PROP		NUMBER(10)	NOT NULL
);

CREATE TABLE ARTA (
ARTA_codigo		NUMBER(10)	NOT NULL,
ARTA_puerta		VARCHAR2(1)	NOT NULL,
ARTA_asiento		NUMBER(10)	NOT NULL,
ARTA_precio		NUMBER(38)	NOT NULL,
FK_AREA		NUMBER(10)	NOT NULL,
FK_TAQU		NUMBER(10)	NOT NULL
);

CREATE TABLE PISO (
PISO_codigo		NUMBER(10)	NOT NULL,
PISO_tipo		VARCHAR2(20)	NOT NULL,
FK_AREA		NUMBER(10)
);

CREATE TABLE CAEJ (
CAEJ_codigo		NUMBER(10)	NOT NULL,
CAEJ_puesto_partida		NUMBER(16)	NOT NULL,
CAEJ_num_ejemplar		NUMBER(20)	NOT NULL,
CAEJ_posicion		NUMBER(16)	NOT NULL,
CAEJ_velocidad		NUMBER(5)	NOT NULL,
CAEJ_cuerpo		NUMBER(10)	NOT NULL,
CAEJ_retiro		VARCHAR2(5),
CAEJ_num_llamado		NUMBER(16)	NOT NULL,
CAEJ_fecha_ins		DATE	NOT NULL,
CAEJ_monto_ins		NUMBER(10)	NOT NULL,
CAEJ_fecha_limite_ins		DATE	NOT NULL,
CAEJ_favorito		VARCHAR2(5),
FK_EJEM		NUMBER(10)	NOT NULL,
FK_CARR		NUMBER(10)	NOT NULL,
FK_HORA		NUMBER(10),
FK_JINE		NUMBER(10)	NOT NULL
);

CREATE TABLE EJEMPLAR (
EJEM_codigo		NUMBER(10)	NOT NULL,
EJEM_nombre		VARCHAR2(20)	NOT NULL,
EJEM_pelaje		VARCHAR2(20)	NOT NULL,
EJEM_fecha_nac		DATE	NOT NULL,
EJEM_sexo		VARCHAR2(5)	NOT NULL,
EJEM_tatuaje		VARCHAR2(20)	NOT NULL,
EJEM_raza		VARCHAR2(20),
FK_EJEM_M		NUMBER(10),
FK_EJEM_P		NUMBER(10),
FK_HARA		NUMBER(10)	NOT NULL,
FK_PUES		NUMBER(10)	NOT NULL
);

CREATE TABLE PROPIETARIO (
PROP_codigo		NUMBER(10)	NOT NULL,
PROP_nombre		VARCHAR2(10)	NOT NULL,
PROP_apellido		VARCHAR2(10)	NOT NULL,
PROP_cedula		NUMBER(10)	NOT NULL,
PROP_fecha_nac		DATE	NOT NULL,
PROP_email		VARCHAR2(50)	NOT NULL,
FK_LUGA		NUMBER(10)	NOT NULL
);

CREATE TABLE ENTRENADOR (
ENTR_codigo		NUMBER(10)	NOT NULL,
ENTR_nombre		VARCHAR2(20)	NOT NULL,
ENTR_apellido		VARCHAR2(20)	NOT NULL
);

CREATE TABLE VETERINARIO (
VETE_codigo		NUMBER(10)	NOT NULL,
VETE_nombre		VARCHAR2(20)	NOT NULL,
VETE_apellido		VARCHAR2(20)	NOT NULL
);

CREATE TABLE JINETE (
JINE_codigo		NUMBER(10)	NOT NULL,
JINE_nombre		VARCHAR2(20)	NOT NULL,
JINE_apellido		VARCHAR2(20)	NOT NULL,
JINE_fecha_nac		DATE	NOT NULL,
JINE_cedula		NUMBER(10)	NOT NULL,
JINE_altura		NUMBER(20)	NOT NULL,
JINE_profesional		VARCHAR2(5)	NOT NULL
);

CREATE TABLE INVITADO (
INVI_codigo		NUMBER(10)	NOT NULL,
INVI_nombre		VARCHAR2(20)	NOT NULL,
INVI_apellido		VARCHAR2(20)	NOT NULL,
INVI_tipo		VARCHAR2(20)	NOT NULL
);

CREATE TABLE TAQUILLA (
TAQU_codigo		NUMBER(10)	NOT NULL,
TAQU_tipo		VARCHAR2(20)	NOT NULL
);

CREATE TABLE IMCA (
IMCA_codigo		NUMBER(10)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_IMPL		NUMBER(10)	NOT NULL
);

CREATE TABLE IMPLEMENTO (
IMPL_codigo		NUMBER(10)	NOT NULL,
IMPL_nombre		VARCHAR2(20)	NOT NULL,
IMPL_tipo		VARCHAR2(2)
);

CREATE TABLE POCA (
POCA_codigo		NUMBER(10)	NOT NULL,
POCA_posicion		NUMBER(16)	NOT NULL,
POCA_tiempo		DATE	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_POST		NUMBER(10)	NOT NULL
);

CREATE TABLE POSTE (
POST_codigo		NUMBER(10)	NOT NULL,
POST_metro		NUMBER(38)	NOT NULL
);

CREATE TABLE CAME (
CAME_codigo		NUMBER(10)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_MEDI		NUMBER(10)	NOT NULL
);

CREATE TABLE MEDICAMENTO (
MEDI_codigo		NUMBER(10)	NOT NULL,
MEDI_nombre		VARCHAR2(20)	NOT NULL
);

CREATE TABLE ENCA (
ENCA_codigo		NUMBER(10)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_ENFE		NUMBER(10)	NOT NULL
);

CREATE TABLE ENFERMEDAD (
ENFE_codigo		NUMBER(10)	NOT NULL,
ENFE_nombre		VARCHAR2(20)	NOT NULL,
ENFE_descripcion		NUMBER(38)	NOT NULL
);

CREATE TABLE PUESTO (
PUES_codigo		NUMBER(10)	NOT NULL,
PUES_fecha_inicio		DATE	NOT NULL,
PUES_fecha_fin		DATE,
PUES_numero		NUMBER(20)	NOT NULL,
FK_CABA		NUMBER(10)	NOT NULL
);

CREATE TABLE CABALLERIZA (
CABA_codigo		NUMBER(10)	NOT NULL,
CABA_nombre		VARCHAR2(20)	NOT NULL,
FK_ENTR		NUMBER(10)	NOT NULL,
FK_VETE		NUMBER(10)	NOT NULL
);

CREATE TABLE EJTR (
EJTR_codigo		NUMBER(10)	NOT NULL,
EJTR_tiempo		NUMBER(20)	NOT NULL,
EJTR_distancia		NUMBER(10)	NOT NULL,
FK_EJEM		NUMBER(10)	NOT NULL,
FK_TRAQ		NUMBER(10)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL
);

CREATE TABLE TRAQUEO (
TRAQ_codigo		NUMBER(10)	NOT NULL,
TRAQ_rematador		VARCHAR2(10)	NOT NULL,
TRAQ_fecha		DATE	NOT NULL
);

CREATE TABLE ENVE (
ENVE_codigo		NUMBER(10)	NOT NULL,
FK_VETE		NUMBER(10)	NOT NULL,
FK_ENFE		NUMBER(10)	NOT NULL
);

CREATE TABLE CAAP (
CAAP_codigo		NUMBER(10)	NOT NULL,
CAAP_monto		NUMBER(38)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL,
FK_TAAP		NUMBER(10)	NOT NULL
);

CREATE TABLE USUARIO (
USUA_codigo		NUMBER(10)	NOT NULL,
USUA_nombre		VARCHAR2(20)	NOT NULL,
USUA_clave		VARCHAR2(20)	NOT NULL,
FK_PROP		NUMBER(10),
FK_ENTR		NUMBER(10),
FK_VETE		NUMBER(10),
FK_JINE		NUMBER(10),
FK_INVI		NUMBER(10)
);

CREATE TABLE ROL (
ROL_codigo		NUMBER(10)	NOT NULL,
ROL_nombre		VARCHAR2(20)	NOT NULL,
ROL_permiso		VARCHAR2(10)	NOT NULL
);

CREATE TABLE TAAP (
TAAP_codigo		NUMBER(10)	NOT NULL,
TAAP_precio		NUMBER(10)	NOT NULL,
FK_APUE		NUMBER(10)	NOT NULL,
FK_TAQU		NUMBER(10)	NOT NULL
);

CREATE TABLE APUESTA (
APUE_codigo		NUMBER(10)	NOT NULL,
APUE_nombre		VARCHAR2(10)	NOT NULL,
APUE_minimo		NUMBER(5)	NOT NULL,
APUE_regla		VARCHAR2(20)	NOT NULL
);

CREATE TABLE ROUS (
ROUS_codigo		NUMBER(10)	NOT NULL,
FK_USUA		NUMBER(10)	NOT NULL,
FK_ROL		NUMBER(10)	NOT NULL
);

CREATE TABLE HARAS (
HARA_codigo		NUMBER(10)	NOT NULL,
HARA_nombre		VARCHAR2(15)	NOT NULL,
FK_LUGA		NUMBER(10)	NOT NULL
);

CREATE TABLE UNIFORME (
UNIF_codigo		NUMBER(10)	NOT NULL,
UNIF_parte		VARCHAR2(15)	NOT NULL
);

CREATE TABLE PREMIO (
PREM_codigo		NUMBER(10)	NOT NULL,
PREM_lugar		VARCHAR2(15)	NOT NULL,
PREM_monto		NUMBER(15)	NOT NULL,
PREM_nombre		VARCHAR2(15)	NOT NULL,
FK_CARR		NUMBER(10)	NOT NULL
);

CREATE TABLE PESO (
PESO_codigo		NUMBER(10)	NOT NULL,
PESO_peso		NUMBER(10)	NOT NULL,
PESO_tipo		VARCHAR2(15)	NOT NULL,
FK_CAEJ		NUMBER(10)	NOT NULL
);