
//INSERTS DE ROUS
//INSERTS DE HARA
//INSERTS DE UNIFORME
//INSERTS DE PUESTO/**/
//INSERTS DE EJEMPLAR*
//INSERTS DE HORA /**/
//INSERTS CARRERA/**/
//INSERTS DE PREMIO
//INSERTS DE CAEJ*
//INSERTS DE PESO
//INSERTS DE IMCA
//INTERS DE POCA
//INSERTS DE EJTR
//INSERTS DE CAME
//INSERTS DE ENCA
//INSERTS DE ENVE
//INSERTS DE COMENTARIO*
//INSERTS DE ARTA*
//INSERTS DE TAAP
//INSERTS DE CAAP
//INSERTS DE HORE*
//INSERTS DE PEAR*
//INSERTS DE COST*
//INSERTS DE PRST*
